// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2hVciA8OShUkhU_KPVLjr-YTrr1OxdZ8',
    appId: '1:1082432487742:web:cf2f899d0d044f24d5ec6f',
    messagingSenderId: '1082432487742',
    projectId: 'studentapp-2d37a',
    authDomain: 'studentapp-2d37a.firebaseapp.com',
    storageBucket: 'studentapp-2d37a.appspot.com',
    measurementId: 'G-CJD617V70L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzTzpvnIj9IKGf06w6pFxqiIi-mNwhr68',
    appId: '1:1082432487742:android:d23048962425a75ad5ec6f',
    messagingSenderId: '1082432487742',
    projectId: 'studentapp-2d37a',
    storageBucket: 'studentapp-2d37a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ymmJhdoPE4Wwc5Kqanzh_SKoB3zP85U',
    appId: '1:1082432487742:ios:98e2365ffa0efab5d5ec6f',
    messagingSenderId: '1082432487742',
    projectId: 'studentapp-2d37a',
    storageBucket: 'studentapp-2d37a.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7ymmJhdoPE4Wwc5Kqanzh_SKoB3zP85U',
    appId: '1:1082432487742:ios:479013fc00018690d5ec6f',
    messagingSenderId: '1082432487742',
    projectId: 'studentapp-2d37a',
    storageBucket: 'studentapp-2d37a.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
